/**
 * ISO 4217 reference data, seeded into the `currency` table.
 *
 * Generated, not hand-maintained. `code` and `minorUnits` come from ICU
 * (`Intl.supportedValuesOf("currency")` and the currency formatter's resolved
 * fraction digits): minor units drive money math, and the widely copied gist
 * snapshot below has them wrong for AMD, CRC, MUR, RSD, TZS and UZS while
 * missing 50 codes entirely. `name`, `symbol` and `symbolNative` come from
 * that gist where it has the code — the thing it is genuinely good at — and
 * from ICU for the rest.
 *
 * ICU follows CLDR, which records what a currency is actually quoted in rather
 * than ISO 4217's formal exponent. The two disagree for a handful of
 * currencies whose subunit has fallen out of use (ALL and AFN are 0 here, 2 in
 * ISO). CLDR is the one that matches what a person expects to type.
 *
 * Source: https://gist.github.com/gp187/4393cbc6dd761225071270c29b341b7b
 */
export interface CurrencyReference {
  code: string;
  /** Fraction digits for the currency's minor unit — JPY 0, PHP 2, KWD 3. */
  minorUnits: number;
  name: string;
  /** Disambiguated for an English reader: CAD is `CA$`, not `$`. */
  symbol: string;
  /** What the currency's own locale prints: CAD is `$`. */
  symbolNative: string;
}

export const currencies: readonly CurrencyReference[] = [
  {
    code: "AED",
    minorUnits: 2,
    name: "United Arab Emirates Dirham",
    symbol: "AED",
    symbolNative: "د.إ.‏",
  },
  {
    code: "AFN",
    minorUnits: 0,
    name: "Afghan Afghani",
    symbol: "Af",
    symbolNative: "؋",
  },
  {
    code: "ALL",
    minorUnits: 0,
    name: "Albanian Lek",
    symbol: "ALL",
    symbolNative: "Lek",
  },
  {
    code: "AMD",
    minorUnits: 2,
    name: "Armenian Dram",
    symbol: "AMD",
    symbolNative: "դր.",
  },
  {
    code: "ANG",
    minorUnits: 2,
    name: "Netherlands Antillean Guilder",
    symbol: "ANG",
    symbolNative: "ANG",
  },
  {
    code: "AOA",
    minorUnits: 2,
    name: "Angolan Kwanza",
    symbol: "Kz",
    symbolNative: "Kz",
  },
  {
    code: "ARS",
    minorUnits: 2,
    name: "Argentine Peso",
    symbol: "AR$",
    symbolNative: "$",
  },
  {
    code: "AUD",
    minorUnits: 2,
    name: "Australian Dollar",
    symbol: "AU$",
    symbolNative: "$",
  },
  {
    code: "AWG",
    minorUnits: 2,
    name: "Aruban Florin",
    symbol: "AWG",
    symbolNative: "AWG",
  },
  {
    code: "AZN",
    minorUnits: 2,
    name: "Azerbaijani Manat",
    symbol: "man.",
    symbolNative: "ман.",
  },
  {
    code: "BAM",
    minorUnits: 2,
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    symbolNative: "KM",
  },
  {
    code: "BBD",
    minorUnits: 2,
    name: "Barbadian Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "BDT",
    minorUnits: 2,
    name: "Bangladeshi Taka",
    symbol: "Tk",
    symbolNative: "৳",
  },
  {
    code: "BGN",
    minorUnits: 2,
    name: "Bulgarian Lev",
    symbol: "BGN",
    symbolNative: "лв.",
  },
  {
    code: "BHD",
    minorUnits: 3,
    name: "Bahraini Dinar",
    symbol: "BD",
    symbolNative: "د.ب.‏",
  },
  {
    code: "BIF",
    minorUnits: 0,
    name: "Burundian Franc",
    symbol: "FBu",
    symbolNative: "FBu",
  },
  {
    code: "BMD",
    minorUnits: 2,
    name: "Bermudan Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "BND",
    minorUnits: 2,
    name: "Brunei Dollar",
    symbol: "BN$",
    symbolNative: "$",
  },
  {
    code: "BOB",
    minorUnits: 2,
    name: "Bolivian Boliviano",
    symbol: "Bs",
    symbolNative: "Bs",
  },
  {
    code: "BRL",
    minorUnits: 2,
    name: "Brazilian Real",
    symbol: "R$",
    symbolNative: "R$",
  },
  {
    code: "BSD",
    minorUnits: 2,
    name: "Bahamian Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "BTN",
    minorUnits: 2,
    name: "Bhutanese Ngultrum",
    symbol: "BTN",
    symbolNative: "BTN",
  },
  {
    code: "BWP",
    minorUnits: 2,
    name: "Botswanan Pula",
    symbol: "BWP",
    symbolNative: "P",
  },
  {
    code: "BYN",
    minorUnits: 2,
    name: "Belarusian Ruble",
    symbol: "BYN",
    symbolNative: "BYN",
  },
  {
    code: "BZD",
    minorUnits: 2,
    name: "Belize Dollar",
    symbol: "BZ$",
    symbolNative: "$",
  },
  {
    code: "CAD",
    minorUnits: 2,
    name: "Canadian Dollar",
    symbol: "CA$",
    symbolNative: "$",
  },
  {
    code: "CDF",
    minorUnits: 2,
    name: "Congolese Franc",
    symbol: "CDF",
    symbolNative: "FrCD",
  },
  {
    code: "CHF",
    minorUnits: 2,
    name: "Swiss Franc",
    symbol: "CHF",
    symbolNative: "CHF",
  },
  {
    code: "CLP",
    minorUnits: 0,
    name: "Chilean Peso",
    symbol: "CL$",
    symbolNative: "$",
  },
  {
    code: "CNY",
    minorUnits: 2,
    name: "Chinese Yuan",
    symbol: "CN¥",
    symbolNative: "CN¥",
  },
  {
    code: "COP",
    minorUnits: 0,
    name: "Colombian Peso",
    symbol: "CO$",
    symbolNative: "$",
  },
  {
    code: "CRC",
    minorUnits: 2,
    name: "Costa Rican Colón",
    symbol: "₡",
    symbolNative: "₡",
  },
  {
    code: "CUC",
    minorUnits: 2,
    name: "Cuban Convertible Peso",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "CUP",
    minorUnits: 2,
    name: "Cuban Peso",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "CVE",
    minorUnits: 2,
    name: "Cape Verdean Escudo",
    symbol: "CV$",
    symbolNative: "CV$",
  },
  {
    code: "CZK",
    minorUnits: 2,
    name: "Czech Republic Koruna",
    symbol: "Kč",
    symbolNative: "Kč",
  },
  {
    code: "DJF",
    minorUnits: 0,
    name: "Djiboutian Franc",
    symbol: "Fdj",
    symbolNative: "Fdj",
  },
  {
    code: "DKK",
    minorUnits: 2,
    name: "Danish Krone",
    symbol: "Dkr",
    symbolNative: "kr",
  },
  {
    code: "DOP",
    minorUnits: 2,
    name: "Dominican Peso",
    symbol: "RD$",
    symbolNative: "RD$",
  },
  {
    code: "DZD",
    minorUnits: 2,
    name: "Algerian Dinar",
    symbol: "DA",
    symbolNative: "د.ج.‏",
  },
  {
    code: "EGP",
    minorUnits: 2,
    name: "Egyptian Pound",
    symbol: "EGP",
    symbolNative: "ج.م.‏",
  },
  {
    code: "ERN",
    minorUnits: 2,
    name: "Eritrean Nakfa",
    symbol: "Nfk",
    symbolNative: "Nfk",
  },
  {
    code: "ETB",
    minorUnits: 2,
    name: "Ethiopian Birr",
    symbol: "Br",
    symbolNative: "Br",
  },
  {
    code: "EUR",
    minorUnits: 2,
    name: "Euro",
    symbol: "€",
    symbolNative: "€",
  },
  {
    code: "FJD",
    minorUnits: 2,
    name: "Fijian Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "FKP",
    minorUnits: 2,
    name: "Falkland Islands Pound",
    symbol: "£",
    symbolNative: "£",
  },
  {
    code: "GBP",
    minorUnits: 2,
    name: "British Pound Sterling",
    symbol: "£",
    symbolNative: "£",
  },
  {
    code: "GEL",
    minorUnits: 2,
    name: "Georgian Lari",
    symbol: "GEL",
    symbolNative: "GEL",
  },
  {
    code: "GHS",
    minorUnits: 2,
    name: "Ghanaian Cedi",
    symbol: "GH₵",
    symbolNative: "GH₵",
  },
  {
    code: "GIP",
    minorUnits: 2,
    name: "Gibraltar Pound",
    symbol: "£",
    symbolNative: "£",
  },
  {
    code: "GMD",
    minorUnits: 2,
    name: "Gambian Dalasi",
    symbol: "GMD",
    symbolNative: "GMD",
  },
  {
    code: "GNF",
    minorUnits: 0,
    name: "Guinean Franc",
    symbol: "FG",
    symbolNative: "FG",
  },
  {
    code: "GTQ",
    minorUnits: 2,
    name: "Guatemalan Quetzal",
    symbol: "GTQ",
    symbolNative: "Q",
  },
  {
    code: "GYD",
    minorUnits: 2,
    name: "Guyanaese Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "HKD",
    minorUnits: 2,
    name: "Hong Kong Dollar",
    symbol: "HK$",
    symbolNative: "$",
  },
  {
    code: "HNL",
    minorUnits: 2,
    name: "Honduran Lempira",
    symbol: "HNL",
    symbolNative: "L",
  },
  {
    code: "HRK",
    minorUnits: 2,
    name: "Croatian Kuna",
    symbol: "kn",
    symbolNative: "kn",
  },
  {
    code: "HTG",
    minorUnits: 2,
    name: "Haitian Gourde",
    symbol: "HTG",
    symbolNative: "HTG",
  },
  {
    code: "HUF",
    minorUnits: 0,
    name: "Hungarian Forint",
    symbol: "Ft",
    symbolNative: "Ft",
  },
  {
    code: "IDR",
    minorUnits: 0,
    name: "Indonesian Rupiah",
    symbol: "Rp",
    symbolNative: "Rp",
  },
  {
    code: "ILS",
    minorUnits: 2,
    name: "Israeli New Sheqel",
    symbol: "₪",
    symbolNative: "₪",
  },
  {
    code: "INR",
    minorUnits: 2,
    name: "Indian Rupee",
    symbol: "Rs",
    symbolNative: "টকা",
  },
  {
    code: "IQD",
    minorUnits: 0,
    name: "Iraqi Dinar",
    symbol: "IQD",
    symbolNative: "د.ع.‏",
  },
  {
    code: "IRR",
    minorUnits: 0,
    name: "Iranian Rial",
    symbol: "IRR",
    symbolNative: "﷼",
  },
  {
    code: "ISK",
    minorUnits: 0,
    name: "Icelandic Króna",
    symbol: "Ikr",
    symbolNative: "kr",
  },
  {
    code: "JMD",
    minorUnits: 2,
    name: "Jamaican Dollar",
    symbol: "J$",
    symbolNative: "$",
  },
  {
    code: "JOD",
    minorUnits: 3,
    name: "Jordanian Dinar",
    symbol: "JD",
    symbolNative: "د.أ.‏",
  },
  {
    code: "JPY",
    minorUnits: 0,
    name: "Japanese Yen",
    symbol: "¥",
    symbolNative: "￥",
  },
  {
    code: "KES",
    minorUnits: 2,
    name: "Kenyan Shilling",
    symbol: "Ksh",
    symbolNative: "Ksh",
  },
  {
    code: "KGS",
    minorUnits: 2,
    name: "Kyrgyz Som",
    symbol: "⃀",
    symbolNative: "⃀",
  },
  {
    code: "KHR",
    minorUnits: 2,
    name: "Cambodian Riel",
    symbol: "KHR",
    symbolNative: "៛",
  },
  {
    code: "KMF",
    minorUnits: 0,
    name: "Comorian Franc",
    symbol: "CF",
    symbolNative: "FC",
  },
  {
    code: "KPW",
    minorUnits: 0,
    name: "North Korean Won",
    symbol: "₩",
    symbolNative: "₩",
  },
  {
    code: "KRW",
    minorUnits: 0,
    name: "South Korean Won",
    symbol: "₩",
    symbolNative: "₩",
  },
  {
    code: "KWD",
    minorUnits: 3,
    name: "Kuwaiti Dinar",
    symbol: "KD",
    symbolNative: "د.ك.‏",
  },
  {
    code: "KYD",
    minorUnits: 2,
    name: "Cayman Islands Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "KZT",
    minorUnits: 2,
    name: "Kazakhstani Tenge",
    symbol: "KZT",
    symbolNative: "тңг.",
  },
  {
    code: "LAK",
    minorUnits: 0,
    name: "Laotian Kip",
    symbol: "₭",
    symbolNative: "₭",
  },
  {
    code: "LBP",
    minorUnits: 0,
    name: "Lebanese Pound",
    symbol: "LB£",
    symbolNative: "ل.ل.‏",
  },
  {
    code: "LKR",
    minorUnits: 2,
    name: "Sri Lankan Rupee",
    symbol: "SLRs",
    symbolNative: "SL Re",
  },
  {
    code: "LRD",
    minorUnits: 2,
    name: "Liberian Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "LSL",
    minorUnits: 2,
    name: "Lesotho Loti",
    symbol: "LSL",
    symbolNative: "LSL",
  },
  {
    code: "LYD",
    minorUnits: 3,
    name: "Libyan Dinar",
    symbol: "LD",
    symbolNative: "د.ل.‏",
  },
  {
    code: "MAD",
    minorUnits: 2,
    name: "Moroccan Dirham",
    symbol: "MAD",
    symbolNative: "د.م.‏",
  },
  {
    code: "MDL",
    minorUnits: 2,
    name: "Moldovan Leu",
    symbol: "MDL",
    symbolNative: "MDL",
  },
  {
    code: "MGA",
    minorUnits: 0,
    name: "Malagasy Ariary",
    symbol: "MGA",
    symbolNative: "MGA",
  },
  {
    code: "MKD",
    minorUnits: 2,
    name: "Macedonian Denar",
    symbol: "MKD",
    symbolNative: "MKD",
  },
  {
    code: "MMK",
    minorUnits: 0,
    name: "Myanma Kyat",
    symbol: "MMK",
    symbolNative: "K",
  },
  {
    code: "MNT",
    minorUnits: 2,
    name: "Mongolian Tugrik",
    symbol: "₮",
    symbolNative: "₮",
  },
  {
    code: "MOP",
    minorUnits: 2,
    name: "Macanese Pataca",
    symbol: "MOP$",
    symbolNative: "MOP$",
  },
  {
    code: "MRU",
    minorUnits: 2,
    name: "Mauritanian Ouguiya",
    symbol: "MRU",
    symbolNative: "MRU",
  },
  {
    code: "MUR",
    minorUnits: 2,
    name: "Mauritian Rupee",
    symbol: "MURs",
    symbolNative: "MURs",
  },
  {
    code: "MVR",
    minorUnits: 2,
    name: "Maldivian Rufiyaa",
    symbol: "MVR",
    symbolNative: "MVR",
  },
  {
    code: "MWK",
    minorUnits: 2,
    name: "Malawian Kwacha",
    symbol: "MWK",
    symbolNative: "MWK",
  },
  {
    code: "MXN",
    minorUnits: 2,
    name: "Mexican Peso",
    symbol: "MX$",
    symbolNative: "$",
  },
  {
    code: "MYR",
    minorUnits: 2,
    name: "Malaysian Ringgit",
    symbol: "RM",
    symbolNative: "RM",
  },
  {
    code: "MZN",
    minorUnits: 2,
    name: "Mozambican Metical",
    symbol: "MTn",
    symbolNative: "MTn",
  },
  {
    code: "NAD",
    minorUnits: 2,
    name: "Namibian Dollar",
    symbol: "N$",
    symbolNative: "N$",
  },
  {
    code: "NGN",
    minorUnits: 2,
    name: "Nigerian Naira",
    symbol: "₦",
    symbolNative: "₦",
  },
  {
    code: "NIO",
    minorUnits: 2,
    name: "Nicaraguan Córdoba",
    symbol: "C$",
    symbolNative: "C$",
  },
  {
    code: "NOK",
    minorUnits: 2,
    name: "Norwegian Krone",
    symbol: "Nkr",
    symbolNative: "kr",
  },
  {
    code: "NPR",
    minorUnits: 2,
    name: "Nepalese Rupee",
    symbol: "NPRs",
    symbolNative: "नेरू",
  },
  {
    code: "NZD",
    minorUnits: 2,
    name: "New Zealand Dollar",
    symbol: "NZ$",
    symbolNative: "$",
  },
  {
    code: "OMR",
    minorUnits: 3,
    name: "Omani Rial",
    symbol: "OMR",
    symbolNative: "ر.ع.‏",
  },
  {
    code: "PAB",
    minorUnits: 2,
    name: "Panamanian Balboa",
    symbol: "B/.",
    symbolNative: "B/.",
  },
  {
    code: "PEN",
    minorUnits: 2,
    name: "Peruvian Nuevo Sol",
    symbol: "S/.",
    symbolNative: "S/.",
  },
  {
    code: "PGK",
    minorUnits: 2,
    name: "Papua New Guinean Kina",
    symbol: "PGK",
    symbolNative: "PGK",
  },
  {
    code: "PHP",
    minorUnits: 2,
    name: "Philippine Peso",
    symbol: "₱",
    symbolNative: "₱",
  },
  {
    code: "PKR",
    minorUnits: 0,
    name: "Pakistani Rupee",
    symbol: "PKRs",
    symbolNative: "₨",
  },
  {
    code: "PLN",
    minorUnits: 2,
    name: "Polish Zloty",
    symbol: "zł",
    symbolNative: "zł",
  },
  {
    code: "PYG",
    minorUnits: 0,
    name: "Paraguayan Guarani",
    symbol: "₲",
    symbolNative: "₲",
  },
  {
    code: "QAR",
    minorUnits: 2,
    name: "Qatari Rial",
    symbol: "QR",
    symbolNative: "ر.ق.‏",
  },
  {
    code: "RON",
    minorUnits: 2,
    name: "Romanian Leu",
    symbol: "RON",
    symbolNative: "RON",
  },
  {
    code: "RSD",
    minorUnits: 2,
    name: "Serbian Dinar",
    symbol: "din.",
    symbolNative: "дин.",
  },
  {
    code: "RUB",
    minorUnits: 2,
    name: "Russian Ruble",
    symbol: "RUB",
    symbolNative: "руб.",
  },
  {
    code: "RWF",
    minorUnits: 0,
    name: "Rwandan Franc",
    symbol: "RWF",
    symbolNative: "FR",
  },
  {
    code: "SAR",
    minorUnits: 2,
    name: "Saudi Riyal",
    symbol: "SR",
    symbolNative: "ر.س.‏",
  },
  {
    code: "SBD",
    minorUnits: 2,
    name: "Solomon Islands Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "SCR",
    minorUnits: 2,
    name: "Seychellois Rupee",
    symbol: "SCR",
    symbolNative: "SCR",
  },
  {
    code: "SDG",
    minorUnits: 2,
    name: "Sudanese Pound",
    symbol: "SDG",
    symbolNative: "SDG",
  },
  {
    code: "SEK",
    minorUnits: 2,
    name: "Swedish Krona",
    symbol: "Skr",
    symbolNative: "kr",
  },
  {
    code: "SGD",
    minorUnits: 2,
    name: "Singapore Dollar",
    symbol: "S$",
    symbolNative: "$",
  },
  {
    code: "SHP",
    minorUnits: 2,
    name: "St. Helena Pound",
    symbol: "£",
    symbolNative: "£",
  },
  {
    code: "SLE",
    minorUnits: 2,
    name: "Sierra Leonean Leone",
    symbol: "SLE",
    symbolNative: "SLE",
  },
  {
    code: "SLL",
    minorUnits: 0,
    name: "Sierra Leonean Leone (1964—2022)",
    symbol: "SLL",
    symbolNative: "SLL",
  },
  {
    code: "SOS",
    minorUnits: 0,
    name: "Somali Shilling",
    symbol: "Ssh",
    symbolNative: "Ssh",
  },
  {
    code: "SRD",
    minorUnits: 2,
    name: "Surinamese Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "SSP",
    minorUnits: 2,
    name: "South Sudanese Pound",
    symbol: "£",
    symbolNative: "£",
  },
  {
    code: "STN",
    minorUnits: 2,
    name: "São Tomé & Príncipe Dobra",
    symbol: "Db",
    symbolNative: "Db",
  },
  {
    code: "SVC",
    minorUnits: 2,
    name: "Salvadoran Colón",
    symbol: "SVC",
    symbolNative: "SVC",
  },
  {
    code: "SYP",
    minorUnits: 0,
    name: "Syrian Pound",
    symbol: "SY£",
    symbolNative: "ل.س.‏",
  },
  {
    code: "SZL",
    minorUnits: 2,
    name: "Swazi Lilangeni",
    symbol: "SZL",
    symbolNative: "SZL",
  },
  {
    code: "THB",
    minorUnits: 2,
    name: "Thai Baht",
    symbol: "฿",
    symbolNative: "฿",
  },
  {
    code: "TJS",
    minorUnits: 2,
    name: "Tajikistani Somoni",
    symbol: "TJS",
    symbolNative: "TJS",
  },
  {
    code: "TMT",
    minorUnits: 2,
    name: "Turkmenistani Manat",
    symbol: "TMT",
    symbolNative: "TMT",
  },
  {
    code: "TND",
    minorUnits: 3,
    name: "Tunisian Dinar",
    symbol: "DT",
    symbolNative: "د.ت.‏",
  },
  {
    code: "TOP",
    minorUnits: 2,
    name: "Tongan Paʻanga",
    symbol: "T$",
    symbolNative: "T$",
  },
  {
    code: "TRY",
    minorUnits: 2,
    name: "Turkish Lira",
    symbol: "TL",
    symbolNative: "TL",
  },
  {
    code: "TTD",
    minorUnits: 2,
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    symbolNative: "$",
  },
  {
    code: "TWD",
    minorUnits: 2,
    name: "New Taiwan Dollar",
    symbol: "NT$",
    symbolNative: "NT$",
  },
  {
    code: "TZS",
    minorUnits: 2,
    name: "Tanzanian Shilling",
    symbol: "TSh",
    symbolNative: "TSh",
  },
  {
    code: "UAH",
    minorUnits: 2,
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    symbolNative: "₴",
  },
  {
    code: "UGX",
    minorUnits: 0,
    name: "Ugandan Shilling",
    symbol: "USh",
    symbolNative: "USh",
  },
  {
    code: "USD",
    minorUnits: 2,
    name: "US Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "UYU",
    minorUnits: 2,
    name: "Uruguayan Peso",
    symbol: "$U",
    symbolNative: "$",
  },
  {
    code: "UZS",
    minorUnits: 2,
    name: "Uzbekistan Som",
    symbol: "UZS",
    symbolNative: "UZS",
  },
  {
    code: "VES",
    minorUnits: 2,
    name: "Venezuelan Bolívar",
    symbol: "VES",
    symbolNative: "VES",
  },
  {
    code: "VND",
    minorUnits: 0,
    name: "Vietnamese Dong",
    symbol: "₫",
    symbolNative: "₫",
  },
  {
    code: "VUV",
    minorUnits: 0,
    name: "Vanuatu Vatu",
    symbol: "VUV",
    symbolNative: "VUV",
  },
  {
    code: "WST",
    minorUnits: 2,
    name: "Samoan Tala",
    symbol: "WST",
    symbolNative: "WST",
  },
  {
    code: "XAF",
    minorUnits: 0,
    name: "CFA Franc BEAC",
    symbol: "FCFA",
    symbolNative: "FCFA",
  },
  {
    code: "XCD",
    minorUnits: 2,
    name: "East Caribbean Dollar",
    symbol: "$",
    symbolNative: "$",
  },
  {
    code: "XCG",
    minorUnits: 2,
    name: "Caribbean guilder",
    symbol: "Cg.",
    symbolNative: "Cg.",
  },
  {
    code: "XDR",
    minorUnits: 2,
    name: "Special Drawing Rights",
    symbol: "XDR",
    symbolNative: "XDR",
  },
  {
    code: "XOF",
    minorUnits: 0,
    name: "CFA Franc BCEAO",
    symbol: "CFA",
    symbolNative: "CFA",
  },
  {
    code: "XPF",
    minorUnits: 0,
    name: "CFP Franc",
    symbol: "CFPF",
    symbolNative: "CFPF",
  },
  {
    code: "XSU",
    minorUnits: 2,
    name: "Sucre",
    symbol: "XSU",
    symbolNative: "XSU",
  },
  {
    code: "YER",
    minorUnits: 0,
    name: "Yemeni Rial",
    symbol: "YR",
    symbolNative: "ر.ي.‏",
  },
  {
    code: "ZAR",
    minorUnits: 2,
    name: "South African Rand",
    symbol: "R",
    symbolNative: "R",
  },
  {
    code: "ZMW",
    minorUnits: 2,
    name: "Zambian Kwacha",
    symbol: "ZK",
    symbolNative: "ZK",
  },
  {
    code: "ZWG",
    minorUnits: 2,
    name: "Zimbabwean Gold",
    symbol: "ZWG",
    symbolNative: "ZWG",
  },
  {
    code: "ZWL",
    minorUnits: 2,
    name: "Zimbabwean Dollar (2009–2024)",
    symbol: "ZWL",
    symbolNative: "ZWL",
  },
];
