// Generated by the plugin in ../tsdown.config.ts.
declare module "virtual:post-migration-scripts" {
  import type { DiscoveredPostMigration } from "@masdan/db/dev-scripts/post-migrate/discover";

  const scripts: DiscoveredPostMigration[];
  export default scripts;
}
