import type { CardProduct } from "../vocabulary";

// Reference: https://www.unionbankph.com/cards/credit-card
export const UNIONBANK_PRODUCTS: readonly CardProduct[] = [
  {
    aliases: ["Rewards Visa", "Rewards Platinum Visa"],
    displayName: "Rewards Visa Platinum",
    issuerKey: "unionbank",
    key: "unionbank-rewards-visa-platinum",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#1c2c55", "#0f1936"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Rewards Mastercard"],
    displayName: "Rewards Platinum Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-rewards-platinum-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#1c2c55", "#0f1936"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["U Platinum", "U Visa"],
    displayName: "U Platinum Visa",
    issuerKey: "unionbank",
    key: "unionbank-u-platinum-visa",
    network: "visa",
    visual: {
      accent: "#9fb4d8",
      background: {
        angle: 135,
        stops: ["#1c1d22", "#0b0b0d"],
      },
      foreground: "light",
      monogram: "U",
      motif: "oversized-letter",
      palette: ["#a9c4ec", "#e9bfe0", "#bfe8dc", "#f3e2b0"],
    },
  },
  {
    aliases: ["U Platinum", "U Mastercard"],
    displayName: "U Platinum Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-u-platinum-mastercard",
    network: "mastercard",
    visual: {
      accent: "#9fb4d8",
      background: {
        angle: 135,
        stops: ["#1c1d22", "#0b0b0d"],
      },
      foreground: "light",
      monogram: "U",
      motif: "oversized-letter",
      palette: ["#a9c4ec", "#e9bfe0", "#bfe8dc", "#f3e2b0"],
    },
  },
  {
    aliases: ["Reserve", "Reserve Visa"],
    displayName: "Reserve Visa Infinite",
    issuerKey: "unionbank",
    key: "unionbank-reserve-visa-infinite",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#161616", "#070707"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Reserve", "Reserve Mastercard"],
    displayName: "Reserve World Elite Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-reserve-world-elite-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#161616", "#070707"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Miles+", "Miles Plus", "PremierMiles"],
    displayName: "Miles+ Visa Signature",
    issuerKey: "unionbank",
    key: "unionbank-miles-plus-visa-signature",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#2a2c30", "#141517"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Miles+", "Miles Plus"],
    displayName: "Miles+ World Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-miles-plus-world-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#2a2c30", "#141517"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Cash Back", "Cashback", "Cash Back Platinum Visa"],
    displayName: "Cash Back Visa",
    issuerKey: "unionbank",
    key: "unionbank-cash-back-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#55595e", "#2c2f33"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Cash Back", "Cashback", "Cash Back Mastercard"],
    displayName: "Cash Back Titanium Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-cash-back-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#55595e", "#2c2f33"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Mercury", "Mercury Drug", "Mercury Drug Visa"],
    displayName: "Mercury Visa",
    issuerKey: "unionbank",
    key: "unionbank-mercury-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#c8ccd1", "#a9aeb4"],
      },
      foreground: "dark",
      pattern: "fine-lines",
    },
  },
  {
    aliases: ["S&R", "S and R", "SNR"],
    displayName: "S&R Visa Platinum",
    issuerKey: "unionbank",
    key: "unionbank-s-and-r-visa-platinum",
    network: "visa",
    visual: {
      accent: "#5aa9ff",
      background: {
        angle: 135,
        stops: ["#0d1a4a", "#081030"],
      },
      foreground: "light",
      motif: "horizon",
    },
  },
  {
    aliases: ["Shell", "Shell Power", "Shell Power Visa Platinum"],
    displayName: "Shell Power Visa",
    issuerKey: "unionbank",
    key: "unionbank-shell-power-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#d42a20", "#a81b14"],
      },
      foreground: "light",
      motif: "chevron-stripes",
      palette: ["#fbce07", "#f7941d"],
    },
  },
  {
    aliases: ["Cebu Pacific", "Cebu Pacific Gold Credit Card", "CebPac Gold"],
    displayName: "Cebu Pacific Gold Visa",
    issuerKey: "unionbank",
    key: "unionbank-cebu-pacific-gold-visa",
    network: "visa",
    visual: {
      accent: "#e8d39a",
      background: {
        angle: 135,
        stops: ["#b08934", "#8f6c24"],
      },
      chipTone: "gold",
      foreground: "light",
      motif: "wing-stripe",
    },
  },
  {
    aliases: [
      "Cebu Pacific",
      "Cebu Pacific Platinum Credit Card",
      "CebPac Platinum",
    ],
    displayName: "Cebu Pacific Platinum Visa",
    issuerKey: "unionbank",
    key: "unionbank-cebu-pacific-platinum-visa",
    network: "visa",
    visual: {
      accent: "#c9ced4",
      background: {
        angle: 135,
        stops: ["#4a5058", "#262a2f"],
      },
      foreground: "light",
      motif: "wing-stripe",
    },
  },
  {
    aliases: ["Go Rewards", "Go Rewards Platinum"],
    displayName: "Go Rewards Platinum Visa",
    issuerKey: "unionbank",
    key: "unionbank-go-rewards-platinum-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#8c9299", "#5f656c"],
      },
      foreground: "light",
      pattern: "angular-panels",
    },
  },
  {
    aliases: ["Secured", "Rewards Secured"],
    displayName: "Rewards Secured Credit Card",
    issuerKey: "unionbank",
    key: "unionbank-rewards-secured-credit-card",
    network: "unknown",
    visual: {
      background: {
        angle: 135,
        stops: ["#22335e", "#131e3c"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Platinum Mastercard 552097"],
    displayName: "Platinum Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-platinum-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#3a3d42", "#1b1d20"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Visa Platinum"],
    displayName: "Platinum Visa",
    issuerKey: "unionbank",
    key: "unionbank-platinum-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#1a1a1a", "#0a0a0a"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    displayName: "Gold Mastercard",
    issuerKey: "unionbank",
    key: "unionbank-gold-mastercard",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#b38b38", "#8a6620"],
      },
      chipTone: "gold",
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Visa Gold"],
    displayName: "Gold Visa",
    issuerKey: "unionbank",
    key: "unionbank-gold-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#b38b38", "#8f6c24"],
      },
      chipTone: "gold",
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Visa Classic"],
    displayName: "Classic Visa",
    issuerKey: "unionbank",
    key: "unionbank-classic-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#d9721a", "#b85a10"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Miles+ Platinum", "Miles Plus Platinum"],
    displayName: "Miles+ Platinum Visa",
    issuerKey: "unionbank",
    key: "unionbank-miles-plus-platinum-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#232428", "#101113"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Go Rewards Gold"],
    displayName: "Go Rewards Gold Visa",
    issuerKey: "unionbank",
    key: "unionbank-go-rewards-gold-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#b38b38", "#8f6c24"],
      },
      chipTone: "gold",
      foreground: "light",
      pattern: "angular-panels",
    },
  },
  {
    aliases: ["Lazada"],
    displayName: "Lazada Credit Card",
    issuerKey: "unionbank",
    key: "unionbank-lazada-credit-card",
    network: "mastercard",
    visual: {
      background: {
        angle: 135,
        stops: ["#1c1f7a", "#12145a"],
      },
      foreground: "light",
    },
  },
  {
    aliases: ["PlayEveryday", "Play Everyday"],
    displayName: "PlayEveryday Credit Card",
    issuerKey: "unionbank",
    key: "unionbank-playeveryday-credit-card",
    network: "unknown",
    visual: {
      background: {
        angle: 135,
        stops: ["#34363b", "#1a1b1e"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Corporate Card"],
    displayName: "Corporate Visa",
    issuerKey: "unionbank",
    key: "unionbank-corporate-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#2e3035", "#17181b"],
      },
      foreground: "light",
      monogram: "UB",
      motif: "monogram",
      pattern: "brushed",
    },
  },
  {
    aliases: ["Assumption Alumni"],
    displayName: "Assumption Alumni Association Visa",
    issuerKey: "unionbank",
    key: "unionbank-assumption-alumni-visa",
    network: "visa",
    visual: {
      accent: "#b3202a",
      background: {
        angle: 135,
        stops: ["#1d3f99", "#132b70"],
      },
      foreground: "light",
      motif: "side-band",
      palette: ["#1d3f99", "#f2c230", "#0b6b3a"],
    },
  },
  {
    aliases: ["Ateneo Alumni", "Ateneo"],
    displayName: "Ateneo Alumni Association Visa",
    issuerKey: "unionbank",
    key: "unionbank-ateneo-alumni-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#1b4aa8", "#11337a"],
      },
      foreground: "light",
      pattern: "angular-panels",
    },
  },
  {
    aliases: ["De La Salle Alumni", "DLSU Alumni"],
    displayName: "De La Salle Alumni Visa",
    issuerKey: "unionbank",
    key: "unionbank-de-la-salle-alumni-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#0f6b3a", "#0a4a28"],
      },
      foreground: "light",
      pattern: "angular-panels",
    },
  },
  {
    aliases: ["La Salle Greenhills", "LSGH"],
    displayName: "La Salle Greenhills Visa",
    issuerKey: "unionbank",
    key: "unionbank-la-salle-greenhills-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#2f8a4a", "#1f6636"],
      },
      foreground: "light",
      pattern: "fine-lines",
    },
  },
  {
    aliases: ["UP Alumni", "UPAA"],
    displayName: "University of the Philippines Alumni Association Visa",
    issuerKey: "unionbank",
    key: "unionbank-up-alumni-visa",
    network: "visa",
    visual: {
      accent: "#7b1113",
      background: {
        angle: 135,
        stops: ["#f2a51f", "#e07b1f"],
      },
      foreground: "dark",
      motif: "sunburst",
    },
  },
  {
    aliases: ["Don Bosco Alumni"],
    displayName: "Don Bosco Alumni Association Visa",
    issuerKey: "unionbank",
    key: "unionbank-don-bosco-alumni-visa",
    network: "visa",
    visual: {
      accent: "#2a5ea8",
      background: {
        angle: 135,
        stops: ["#e6eef6", "#c9d9ea"],
      },
      foreground: "dark",
      motif: "medallion",
    },
  },
  {
    aliases: ["SWU Alumni", "Southwestern University"],
    displayName: "Southwestern University Alumni Foundation Visa",
    issuerKey: "unionbank",
    key: "unionbank-swu-alumni-visa",
    network: "visa",
    visual: {
      accent: "#b3202a",
      background: {
        angle: 135,
        stops: ["#f3ede2", "#e6dcc8"],
      },
      foreground: "dark",
      motif: "wave-ribbon",
    },
  },
  {
    aliases: ["CFC FFL", "Couples for Christ"],
    displayName: "Couples for Christ Foundation for Family and Life Visa",
    issuerKey: "unionbank",
    key: "unionbank-cfc-ffl-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#2f6fc0", "#1a4a8a"],
      },
      foreground: "light",
      pattern: "fine-lines",
    },
  },
  {
    aliases: ["WWF"],
    displayName: "World Wide Fund Visa",
    issuerKey: "unionbank",
    key: "unionbank-wwf-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#0b5f7a", "#073f52"],
      },
      foreground: "light",
      pattern: "topographic",
    },
  },
  {
    aliases: ["Mapfre Insular", "Mapfre"],
    displayName: "Mapfre Insular Visa",
    issuerKey: "unionbank",
    key: "unionbank-mapfre-insular-visa",
    network: "visa",
    visual: {
      accent: "#ffffff",
      background: {
        angle: 135,
        stops: ["#c8102e", "#9b0c23"],
      },
      foreground: "light",
      motif: "wave-ribbon",
    },
  },
  {
    aliases: ["Insular Life"],
    displayName: "Insular Life Visa",
    issuerKey: "unionbank",
    key: "unionbank-insular-life-visa",
    network: "visa",
    visual: {
      accent: "#ffffff",
      background: {
        angle: 135,
        stops: ["#e4572e", "#c8102e"],
      },
      foreground: "light",
      motif: "wave-ribbon",
    },
  },
  {
    aliases: ["Burgoo"],
    displayName: "Burgoo Visa",
    issuerKey: "unionbank",
    key: "unionbank-burgoo-visa",
    network: "visa",
    visual: {
      accent: "#f3ede2",
      background: {
        angle: 135,
        stops: ["#b3202a", "#8a1820"],
      },
      foreground: "light",
      motif: "wave-ribbon",
    },
  },
  {
    aliases: ["The North Face", "TNF"],
    displayName: "The North Face Visa",
    issuerKey: "unionbank",
    key: "unionbank-the-north-face-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#5b6b7a", "#2e3a46"],
      },
      foreground: "light",
      pattern: "topographic",
    },
  },
  {
    aliases: ["Home Depot", "CW Home Depot"],
    displayName: "Home Depot Visa",
    issuerKey: "unionbank",
    key: "unionbank-home-depot-visa",
    network: "visa",
    visual: {
      accent: "#1f5fbf",
      background: {
        angle: 135,
        stops: ["#f4f6f9", "#e3e8ef"],
      },
      foreground: "dark",
      pattern: "pixels",
    },
  },
  {
    aliases: ["Riviera Golf Club", "Riviera"],
    displayName: "Riviera Golf Club Visa",
    issuerKey: "unionbank",
    key: "unionbank-riviera-golf-club-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#3f7f3a", "#6a8f2a"],
      },
      foreground: "light",
      pattern: "topographic",
    },
  },
  {
    aliases: ["Suy Sing"],
    displayName: "Suy Sing Visa",
    issuerKey: "unionbank",
    key: "unionbank-suy-sing-visa",
    network: "visa",
    visual: {
      background: {
        angle: 135,
        stops: ["#d1d4d8", "#b3b7bc"],
      },
      foreground: "dark",
      motif: "silk",
    },
  },
  {
    aliases: ["Cebu Parklane", "Parklane"],
    displayName: "Cebu Parklane International Hotel Visa",
    issuerKey: "unionbank",
    key: "unionbank-cebu-parklane-visa",
    network: "visa",
    visual: {
      background: {
        angle: 160,
        stops: ["#2a3f7a", "#c2562a"],
      },
      foreground: "light",
    },
  },
];
