import type { CardIssuer } from "./vocabulary";

// Every card issuer in the Credit Card Association of the Philippines, plus Zed.
export const CARD_ISSUERS: readonly CardIssuer[] = [
  {
    aliases: ["AUB", "Asia United Bank", "Asia United Bank Corporation"],
    brandColor: "#173f8a",
    key: "aub",
    name: "Asia United Bank",
    shortName: "AUB",
  },
  {
    aliases: ["Bank of Commerce", "BankCom", "Bank Com"],
    brandColor: "#1c3f94",
    key: "bankcom",
    name: "Bank of Commerce",
    shortName: "BankCom",
  },
  {
    aliases: ["BDO", "BDO Unibank", "Banco de Oro", "Banco de Oro Unibank"],
    brandColor: "#0033a0",
    key: "bdo",
    name: "BDO Unibank",
    shortName: "BDO",
  },
  {
    aliases: [
      "BPI",
      "Bank of the Philippine Islands",
      "BPI Family Savings Bank",
      "BPI Card Finance",
    ],
    brandColor: "#c8102e",
    key: "bpi",
    name: "Bank of the Philippine Islands",
    shortName: "BPI",
  },
  {
    aliases: [
      "Metrobank",
      "Metro Bank",
      "Metropolitan Bank",
      "Metropolitan Bank and Trust",
      "Metropolitan Bank and Trust Company",
      "Metrobank Card Corporation",
      // PSBank's credit card is issued by Metrobank Card Corporation.
      "PSBank",
      "Philippine Savings Bank",
    ],
    brandColor: "#0038a8",
    key: "metrobank",
    name: "Metrobank",
    shortName: "Metrobank",
  },
  {
    aliases: [
      "UnionBank",
      "Union Bank",
      "UnionBank of the Philippines",
      "Union Bank of the Philippines",
      "UBP",
      // Citi's Philippine consumer cards moved to UnionBank.
      "Citi",
      "Citibank",
    ],
    brandColor: "#f47b20",
    key: "unionbank",
    name: "UnionBank",
    shortName: "UnionBank",
  },
  {
    aliases: [
      "RCBC",
      "RCBC Bankard",
      "RCBC Credit",
      "Bankard",
      "Rizal Commercial Banking Corporation",
    ],
    brandColor: "#003c7d",
    key: "rcbc",
    name: "RCBC",
    shortName: "RCBC",
  },
  {
    aliases: ["Security Bank", "SecurityBank", "Security Bank Corporation"],
    brandColor: "#0b2a5b",
    key: "securitybank",
    name: "Security Bank",
    shortName: "Security Bank",
  },
  {
    aliases: [
      "EastWest",
      "East West",
      "EastWest Bank",
      "East West Bank",
      "East West Banking Corporation",
    ],
    brandColor: "#6b2c91",
    key: "eastwest",
    name: "EastWest Bank",
    shortName: "EastWest",
  },
  {
    aliases: ["Equicom", "Equicom Savings Bank", "Equicom Savings"],
    brandColor: "#0f7a43",
    key: "equicom",
    name: "Equicom Savings Bank",
    shortName: "Equicom",
  },
  {
    aliases: [
      "Home Credit",
      "Home Credit Philippines",
      "HC Consumer Finance",
      "HC Consumer Finance Philippines",
    ],
    brandColor: "#e11931",
    key: "homecredit",
    name: "Home Credit",
    shortName: "Home Credit",
  },
  {
    aliases: [
      "HSBC",
      "HSBC Philippines",
      "Hongkong and Shanghai Banking Corporation",
      "The Hongkong and Shanghai Banking Corporation",
    ],
    brandColor: "#db0011",
    key: "hsbc",
    name: "HSBC",
    shortName: "HSBC",
  },
  {
    aliases: ["Landbank", "Land Bank", "Land Bank of the Philippines", "LBP"],
    brandColor: "#00813e",
    key: "landbank",
    name: "Land Bank of the Philippines",
    shortName: "Landbank",
  },
  {
    aliases: ["Maya", "Maya Bank", "PayMaya"],
    brandColor: "#04b36b",
    key: "maya",
    name: "Maya Bank",
    shortName: "Maya",
  },
  {
    aliases: ["Maybank", "Maybank Philippines", "Malayan Banking"],
    brandColor: "#ffc72c",
    key: "maybank",
    name: "Maybank Philippines",
    shortName: "Maybank",
  },
  {
    aliases: ["Chinabank", "China Bank", "China Banking Corporation"],
    brandColor: "#d71920",
    key: "chinabank",
    name: "Chinabank",
    shortName: "Chinabank",
  },
  {
    aliases: ["PNB", "Philippine National Bank"],
    brandColor: "#00205b",
    key: "pnb",
    name: "Philippine National Bank",
    shortName: "PNB",
  },
  {
    aliases: ["Zed", "Zed Card", "Zed Financial", "Zed Financial PH"],
    brandColor: "#f2ee2e",
    key: "zed",
    name: "Zed",
    shortName: "Zed",
  },
];
