CREATE TABLE "currency" (
	"code" text PRIMARY KEY,
	"enabled" boolean DEFAULT true NOT NULL,
	"minor_units" smallint NOT NULL,
	"name" text NOT NULL,
	"symbol" text NOT NULL,
	"symbol_native" text NOT NULL
);
--> statement-breakpoint
-- Reference rows, not a data backfill: the organization FK below is
-- unsatisfiable until 'PHP' exists, and a migrate-only environment (the test
-- template) never runs post-migration scripts. Frozen here like any other
-- migration; src/reference/currencies.ts is the maintained source, and
-- post-migration-scripts/*_sync_currency_reference.ts reconciles the two.
INSERT INTO "currency" ("code", "minor_units", "name", "symbol", "symbol_native") VALUES
	('AED', 2, 'United Arab Emirates Dirham', 'AED', 'د.إ.‏'),
	('AFN', 0, 'Afghan Afghani', 'Af', '؋'),
	('ALL', 0, 'Albanian Lek', 'ALL', 'Lek'),
	('AMD', 2, 'Armenian Dram', 'AMD', 'դր.'),
	('ANG', 2, 'Netherlands Antillean Guilder', 'ANG', 'ANG'),
	('AOA', 2, 'Angolan Kwanza', 'Kz', 'Kz'),
	('ARS', 2, 'Argentine Peso', 'AR$', '$'),
	('AUD', 2, 'Australian Dollar', 'AU$', '$'),
	('AWG', 2, 'Aruban Florin', 'AWG', 'AWG'),
	('AZN', 2, 'Azerbaijani Manat', 'man.', 'ман.'),
	('BAM', 2, 'Bosnia-Herzegovina Convertible Mark', 'KM', 'KM'),
	('BBD', 2, 'Barbadian Dollar', '$', '$'),
	('BDT', 2, 'Bangladeshi Taka', 'Tk', '৳'),
	('BGN', 2, 'Bulgarian Lev', 'BGN', 'лв.'),
	('BHD', 3, 'Bahraini Dinar', 'BD', 'د.ب.‏'),
	('BIF', 0, 'Burundian Franc', 'FBu', 'FBu'),
	('BMD', 2, 'Bermudan Dollar', '$', '$'),
	('BND', 2, 'Brunei Dollar', 'BN$', '$'),
	('BOB', 2, 'Bolivian Boliviano', 'Bs', 'Bs'),
	('BRL', 2, 'Brazilian Real', 'R$', 'R$'),
	('BSD', 2, 'Bahamian Dollar', '$', '$'),
	('BTN', 2, 'Bhutanese Ngultrum', 'BTN', 'BTN'),
	('BWP', 2, 'Botswanan Pula', 'BWP', 'P'),
	('BYN', 2, 'Belarusian Ruble', 'BYN', 'BYN'),
	('BZD', 2, 'Belize Dollar', 'BZ$', '$'),
	('CAD', 2, 'Canadian Dollar', 'CA$', '$'),
	('CDF', 2, 'Congolese Franc', 'CDF', 'FrCD'),
	('CHF', 2, 'Swiss Franc', 'CHF', 'CHF'),
	('CLP', 0, 'Chilean Peso', 'CL$', '$'),
	('CNY', 2, 'Chinese Yuan', 'CN¥', 'CN¥'),
	('COP', 0, 'Colombian Peso', 'CO$', '$'),
	('CRC', 2, 'Costa Rican Colón', '₡', '₡'),
	('CUC', 2, 'Cuban Convertible Peso', '$', '$'),
	('CUP', 2, 'Cuban Peso', '$', '$'),
	('CVE', 2, 'Cape Verdean Escudo', 'CV$', 'CV$'),
	('CZK', 2, 'Czech Republic Koruna', 'Kč', 'Kč'),
	('DJF', 0, 'Djiboutian Franc', 'Fdj', 'Fdj'),
	('DKK', 2, 'Danish Krone', 'Dkr', 'kr'),
	('DOP', 2, 'Dominican Peso', 'RD$', 'RD$'),
	('DZD', 2, 'Algerian Dinar', 'DA', 'د.ج.‏'),
	('EGP', 2, 'Egyptian Pound', 'EGP', 'ج.م.‏'),
	('ERN', 2, 'Eritrean Nakfa', 'Nfk', 'Nfk'),
	('ETB', 2, 'Ethiopian Birr', 'Br', 'Br'),
	('EUR', 2, 'Euro', '€', '€'),
	('FJD', 2, 'Fijian Dollar', '$', '$'),
	('FKP', 2, 'Falkland Islands Pound', '£', '£'),
	('GBP', 2, 'British Pound Sterling', '£', '£'),
	('GEL', 2, 'Georgian Lari', 'GEL', 'GEL'),
	('GHS', 2, 'Ghanaian Cedi', 'GH₵', 'GH₵'),
	('GIP', 2, 'Gibraltar Pound', '£', '£'),
	('GMD', 2, 'Gambian Dalasi', 'GMD', 'GMD'),
	('GNF', 0, 'Guinean Franc', 'FG', 'FG'),
	('GTQ', 2, 'Guatemalan Quetzal', 'GTQ', 'Q'),
	('GYD', 2, 'Guyanaese Dollar', '$', '$'),
	('HKD', 2, 'Hong Kong Dollar', 'HK$', '$'),
	('HNL', 2, 'Honduran Lempira', 'HNL', 'L'),
	('HRK', 2, 'Croatian Kuna', 'kn', 'kn'),
	('HTG', 2, 'Haitian Gourde', 'HTG', 'HTG'),
	('HUF', 0, 'Hungarian Forint', 'Ft', 'Ft'),
	('IDR', 0, 'Indonesian Rupiah', 'Rp', 'Rp'),
	('ILS', 2, 'Israeli New Sheqel', '₪', '₪'),
	('INR', 2, 'Indian Rupee', 'Rs', 'টকা'),
	('IQD', 0, 'Iraqi Dinar', 'IQD', 'د.ع.‏'),
	('IRR', 0, 'Iranian Rial', 'IRR', '﷼'),
	('ISK', 0, 'Icelandic Króna', 'Ikr', 'kr'),
	('JMD', 2, 'Jamaican Dollar', 'J$', '$'),
	('JOD', 3, 'Jordanian Dinar', 'JD', 'د.أ.‏'),
	('JPY', 0, 'Japanese Yen', '¥', '￥'),
	('KES', 2, 'Kenyan Shilling', 'Ksh', 'Ksh'),
	('KGS', 2, 'Kyrgyz Som', '⃀', '⃀'),
	('KHR', 2, 'Cambodian Riel', 'KHR', '៛'),
	('KMF', 0, 'Comorian Franc', 'CF', 'FC'),
	('KPW', 0, 'North Korean Won', '₩', '₩'),
	('KRW', 0, 'South Korean Won', '₩', '₩'),
	('KWD', 3, 'Kuwaiti Dinar', 'KD', 'د.ك.‏'),
	('KYD', 2, 'Cayman Islands Dollar', '$', '$'),
	('KZT', 2, 'Kazakhstani Tenge', 'KZT', 'тңг.'),
	('LAK', 0, 'Laotian Kip', '₭', '₭'),
	('LBP', 0, 'Lebanese Pound', 'LB£', 'ل.ل.‏'),
	('LKR', 2, 'Sri Lankan Rupee', 'SLRs', 'SL Re'),
	('LRD', 2, 'Liberian Dollar', '$', '$'),
	('LSL', 2, 'Lesotho Loti', 'LSL', 'LSL'),
	('LYD', 3, 'Libyan Dinar', 'LD', 'د.ل.‏'),
	('MAD', 2, 'Moroccan Dirham', 'MAD', 'د.م.‏'),
	('MDL', 2, 'Moldovan Leu', 'MDL', 'MDL'),
	('MGA', 0, 'Malagasy Ariary', 'MGA', 'MGA'),
	('MKD', 2, 'Macedonian Denar', 'MKD', 'MKD'),
	('MMK', 0, 'Myanma Kyat', 'MMK', 'K'),
	('MNT', 2, 'Mongolian Tugrik', '₮', '₮'),
	('MOP', 2, 'Macanese Pataca', 'MOP$', 'MOP$'),
	('MRU', 2, 'Mauritanian Ouguiya', 'MRU', 'MRU'),
	('MUR', 2, 'Mauritian Rupee', 'MURs', 'MURs'),
	('MVR', 2, 'Maldivian Rufiyaa', 'MVR', 'MVR'),
	('MWK', 2, 'Malawian Kwacha', 'MWK', 'MWK'),
	('MXN', 2, 'Mexican Peso', 'MX$', '$'),
	('MYR', 2, 'Malaysian Ringgit', 'RM', 'RM'),
	('MZN', 2, 'Mozambican Metical', 'MTn', 'MTn'),
	('NAD', 2, 'Namibian Dollar', 'N$', 'N$'),
	('NGN', 2, 'Nigerian Naira', '₦', '₦'),
	('NIO', 2, 'Nicaraguan Córdoba', 'C$', 'C$'),
	('NOK', 2, 'Norwegian Krone', 'Nkr', 'kr'),
	('NPR', 2, 'Nepalese Rupee', 'NPRs', 'नेरू'),
	('NZD', 2, 'New Zealand Dollar', 'NZ$', '$'),
	('OMR', 3, 'Omani Rial', 'OMR', 'ر.ع.‏'),
	('PAB', 2, 'Panamanian Balboa', 'B/.', 'B/.'),
	('PEN', 2, 'Peruvian Nuevo Sol', 'S/.', 'S/.'),
	('PGK', 2, 'Papua New Guinean Kina', 'PGK', 'PGK'),
	('PHP', 2, 'Philippine Peso', '₱', '₱'),
	('PKR', 0, 'Pakistani Rupee', 'PKRs', '₨'),
	('PLN', 2, 'Polish Zloty', 'zł', 'zł'),
	('PYG', 0, 'Paraguayan Guarani', '₲', '₲'),
	('QAR', 2, 'Qatari Rial', 'QR', 'ر.ق.‏'),
	('RON', 2, 'Romanian Leu', 'RON', 'RON'),
	('RSD', 2, 'Serbian Dinar', 'din.', 'дин.'),
	('RUB', 2, 'Russian Ruble', 'RUB', 'руб.'),
	('RWF', 0, 'Rwandan Franc', 'RWF', 'FR'),
	('SAR', 2, 'Saudi Riyal', 'SR', 'ر.س.‏'),
	('SBD', 2, 'Solomon Islands Dollar', '$', '$'),
	('SCR', 2, 'Seychellois Rupee', 'SCR', 'SCR'),
	('SDG', 2, 'Sudanese Pound', 'SDG', 'SDG'),
	('SEK', 2, 'Swedish Krona', 'Skr', 'kr'),
	('SGD', 2, 'Singapore Dollar', 'S$', '$'),
	('SHP', 2, 'St. Helena Pound', '£', '£'),
	('SLE', 2, 'Sierra Leonean Leone', 'SLE', 'SLE'),
	('SLL', 0, 'Sierra Leonean Leone (1964—2022)', 'SLL', 'SLL'),
	('SOS', 0, 'Somali Shilling', 'Ssh', 'Ssh'),
	('SRD', 2, 'Surinamese Dollar', '$', '$'),
	('SSP', 2, 'South Sudanese Pound', '£', '£'),
	('STN', 2, 'São Tomé & Príncipe Dobra', 'Db', 'Db'),
	('SVC', 2, 'Salvadoran Colón', 'SVC', 'SVC'),
	('SYP', 0, 'Syrian Pound', 'SY£', 'ل.س.‏'),
	('SZL', 2, 'Swazi Lilangeni', 'SZL', 'SZL'),
	('THB', 2, 'Thai Baht', '฿', '฿'),
	('TJS', 2, 'Tajikistani Somoni', 'TJS', 'TJS'),
	('TMT', 2, 'Turkmenistani Manat', 'TMT', 'TMT'),
	('TND', 3, 'Tunisian Dinar', 'DT', 'د.ت.‏'),
	('TOP', 2, 'Tongan Paʻanga', 'T$', 'T$'),
	('TRY', 2, 'Turkish Lira', 'TL', 'TL'),
	('TTD', 2, 'Trinidad and Tobago Dollar', 'TT$', '$'),
	('TWD', 2, 'New Taiwan Dollar', 'NT$', 'NT$'),
	('TZS', 2, 'Tanzanian Shilling', 'TSh', 'TSh'),
	('UAH', 2, 'Ukrainian Hryvnia', '₴', '₴'),
	('UGX', 0, 'Ugandan Shilling', 'USh', 'USh'),
	('USD', 2, 'US Dollar', '$', '$'),
	('UYU', 2, 'Uruguayan Peso', '$U', '$'),
	('UZS', 2, 'Uzbekistan Som', 'UZS', 'UZS'),
	('VES', 2, 'Venezuelan Bolívar', 'VES', 'VES'),
	('VND', 0, 'Vietnamese Dong', '₫', '₫'),
	('VUV', 0, 'Vanuatu Vatu', 'VUV', 'VUV'),
	('WST', 2, 'Samoan Tala', 'WST', 'WST'),
	('XAF', 0, 'CFA Franc BEAC', 'FCFA', 'FCFA'),
	('XCD', 2, 'East Caribbean Dollar', '$', '$'),
	('XCG', 2, 'Caribbean guilder', 'Cg.', 'Cg.'),
	('XDR', 2, 'Special Drawing Rights', 'XDR', 'XDR'),
	('XOF', 0, 'CFA Franc BCEAO', 'CFA', 'CFA'),
	('XPF', 0, 'CFP Franc', 'CFPF', 'CFPF'),
	('XSU', 2, 'Sucre', 'XSU', 'XSU'),
	('YER', 0, 'Yemeni Rial', 'YR', 'ر.ي.‏'),
	('ZAR', 2, 'South African Rand', 'R', 'R'),
	('ZMW', 2, 'Zambian Kwacha', 'ZK', 'ZK'),
	('ZWG', 2, 'Zimbabwean Gold', 'ZWG', 'ZWG'),
	('ZWL', 2, 'Zimbabwean Dollar (2009–2024)', 'ZWL', 'ZWL')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
ALTER TABLE "organization" ADD COLUMN "default_currency" text DEFAULT 'PHP' NOT NULL;--> statement-breakpoint
ALTER TABLE "organization" ADD COLUMN "timezone" text DEFAULT 'Asia/Manila' NOT NULL;--> statement-breakpoint
ALTER TABLE "organization" ADD CONSTRAINT "organization_default_currency_currency_code_fkey" FOREIGN KEY ("default_currency") REFERENCES "currency"("code") ON DELETE RESTRICT;